### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by MichaelXavier** [michaelt/lens-simple#1]
Hi,

I've got a [project](https://github.com/soostone/uri-bytestring) whose test suite depends on lens-simple that I'm trying to get back into the stack nightlies. I noticed that your build didn't work on 8.0.1 and forked it, but having made no modifications of note, [it built successfully](https://travis-ci.org/MichaelXavier/lens-simple/builds/139520488), so I assume some hackage metadata changed. Anything else needed for a release of a new version of lens-simple?

**Comment by michaelt** [comment]
Hi I saw another stack problem like that on Friday and revised lens simple, but it didn't build with Travis ghc 8 since lens family needed an update.  I corresponded with roconnor who, I see, has updated. At the moment I'm in a remote place  but hope I can get an internet connection and release it tonight or tomorrow.  Why I didn't just upload it Friday, I don't know.

**Comment by michaelt** [comment]
Hi, I uploaded a ghc-8-worthy https://hackage.haskell.org/package/lens-simple-0.1.0.9

**Comment by MichaelXavier** [comment]
Thanks!
